import { Roboto_Flex, Yaldevi } from 'next/font/google';
import './globals.css';
import TitleBar from './components/TitleBar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const robotoFlex = Roboto_Flex({
  subsets: ['latin'],
  variable: '--roboto-flex',
  display: 'swap',
  weight: ['500', '700', '800'],
  // axes: ["wdth"] //figure it out why is not working
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${robotoFlex.className} antialiased bg-[#F9FAFA]`}>
        <TitleBar></TitleBar>
        <div className="w-[70vw] max-w-[700px] mx-auto min-h-screen p-[32px] gap-[48px]">
          {children}
        </div>
      </body>
    </html>
  );
}
